[package]
name = "RSCombat"
version = "0.1.0"
authors = ["kenny"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
druid = "0.7.0"
pcap = { version = "0.8", features = ["capture-stream"] }


